// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherFunc.Data;

#nullable disable

namespace WeatherFunc.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    [Migration("20250826145227_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeatherFunc.Models.WeatherData", b =>
                {
                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<double>("TemperatureC")
                        .HasColumnType("float");

                    b.HasKey("TimestampUtc");

                    b.ToTable("WeatherData");
                });
#pragma warning restore 612, 618
        }
    }
}
